# Generated by Django 4.2.14 on 2024-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=255)),
                ('conflict_resolution_effectiveness', models.CharField(max_length=255)),
                ('information_quality', models.CharField(max_length=255)),
                ('community_service_effectiveness', models.CharField(max_length=255)),
                ('suggestions', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
